[2024-10-15T03:17:20.954+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-10-15T03:17:19.555388+00:00 [queued]>
[2024-10-15T03:17:20.958+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-10-15T03:17:19.555388+00:00 [queued]>
[2024-10-15T03:17:20.958+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-10-15T03:17:20.958+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-10-15T03:17:20.958+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-10-15T03:17:20.963+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-10-15 03:17:19.555388+00:00
[2024-10-15T03:17:20.965+0000] {standard_task_runner.py:55} INFO - Started process 10750 to run task
[2024-10-15T03:17:20.967+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-10-15T03:17:19.555388+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpmxos1k4d']
[2024-10-15T03:17:20.968+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask is_api_available
[2024-10-15T03:17:20.992+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-10-15T03:17:19.555388+00:00 [running]> on host 19419e3f0c68
[2024-10-15T03:17:21.016+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-10-15T03:17:19.555388+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-15T03:17:19.555388+00:00
[2024-10-15T03:17:21.016+0000] {http.py:120} INFO - Poking: api/
[2024-10-15T03:17:21.019+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-10-15T03:17:21.020+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-10-15T03:17:21.122+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2024-10-15T03:17:21.457+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-10-15T03:17:21.473+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20241015T031719, start_date=20241015T031720, end_date=20241015T031721
[2024-10-15T03:17:21.531+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-10-15T03:17:21.556+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
