[2024-10-16T02:15:00.909+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T02:10:00+00:00 [queued]>
[2024-10-16T02:15:00.914+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T02:10:00+00:00 [queued]>
[2024-10-16T02:15:00.914+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T02:15:00.914+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-10-16T02:15:00.914+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T02:15:00.920+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-10-16 02:10:00+00:00
[2024-10-16T02:15:00.923+0000] {standard_task_runner.py:55} INFO - Started process 4270 to run task
[2024-10-16T02:15:00.925+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-10-16T02:10:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpz6bdao6j']
[2024-10-16T02:15:00.925+0000] {standard_task_runner.py:83} INFO - Job 180: Subtask is_api_available
[2024-10-16T02:15:00.954+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T02:10:00+00:00 [running]> on host dcdd4c71b617
[2024-10-16T02:15:00.983+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-10-16T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-16T02:10:00+00:00
[2024-10-16T02:15:00.984+0000] {http.py:120} INFO - Poking: api/
[2024-10-16T02:15:00.987+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-10-16T02:15:00.988+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-10-16T02:15:01.123+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2024-10-16T02:15:01.511+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-10-16T02:15:01.517+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20241016T021000, start_date=20241016T021500, end_date=20241016T021501
[2024-10-16T02:15:01.529+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-10-16T02:15:01.547+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
