[2024-10-15T03:07:48.739+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-10-15T03:07:44.086550+00:00 [queued]>
[2024-10-15T03:07:48.742+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-10-15T03:07:44.086550+00:00 [queued]>
[2024-10-15T03:07:48.743+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-10-15T03:07:48.743+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-10-15T03:07:48.743+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-10-15T03:07:48.747+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-10-15 03:07:44.086550+00:00
[2024-10-15T03:07:48.750+0000] {standard_task_runner.py:55} INFO - Started process 10260 to run task
[2024-10-15T03:07:48.751+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2024-10-15T03:07:44.086550+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp73c4nanf']
[2024-10-15T03:07:48.752+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask store_user
[2024-10-15T03:07:48.775+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2024-10-15T03:07:44.086550+00:00 [running]> on host 19419e3f0c68
[2024-10-15T03:07:48.798+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-10-15T03:07:44.086550+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-15T03:07:44.086550+00:00
[2024-10-15T03:07:48.798+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-10-15T03:07:48.801+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-10-15T03:07:48.802+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 29, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "address"
CONTEXT:  COPY users, line 1: "Natalia,Ivančević,Serbia,ticklishbear103,1022,natalia.ivancevic@example.com"

[2024-10-15T03:07:48.805+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20241015T030744, start_date=20241015T030748, end_date=20241015T030748
[2024-10-15T03:07:48.809+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task store_user (missing data for column "address"
CONTEXT:  COPY users, line 1: "Natalia,Ivančević,Serbia,ticklishbear103,1022,natalia.ivancevic@example.com"
; 10260)
[2024-10-15T03:07:48.814+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-10-15T03:07:48.821+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
